[project]
name = "aoc"
version = "0.1.0"
description = "Advent of code solutions"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pydantic"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
